
import {
    faApple,
    faAudible,
    faDiscord,
    faFacebook,
    faGoogle,
    faInstagram,
    faItunesNote,
    faLinkedin,
    faShopify,
    faWindows,
    faYoutube
} from '@fortawesome/free-brands-svg-icons'
import {
    faAddressBook,
    faAddressCard,
    faBaby,
    faBagShopping,
    faBath,
    faBed,
    faBell,
    faBellConcierge,
    faBicycle,
    faBolt,
    faBook,
    faBookOpenReader,
    faBrain,
    faBriefcase,
    faBroom,
    faBroomBall,
    faBug,
    faBuilding,
    faBurger,
    faBusSimple,
    faCableCar,
    faCalendarDays,
    faCamera,
    faCar,
    faCarSide,
    faChartGantt,
    faCheck,
    faCircleExclamation,
    faCircleUser,
    faCity,
    faClapperboard,
    faClock,
    faCode,
    faComment,
    faComments,
    faCouch,
    faCreditCard,
    faDesktop,
    faDoorOpen,
    faDroplet,
    faDumbbell,
    faEarthAsia,
    faEnvelope,
    faEye,
    faFilter,
    faFire,
    faFish,
    faFlag,
    faFolder,
    faGamepad,
    faGasPump,
    faGift,
    faGlassWater,
    faGopuram,
    faHand,
    faHandHoldingHeart,
    faHandMiddleFinger,
    faHandPeace,
    faHandPointDown,
    faHashtag,
    faHeadphones,
    faHeart,
    faHospital,
    faHotel,
    faHourglassHalf,
    faHouse,
    faIceCream,
    faImage,
    faIndustry,
    faInfinity,
    faKey,
    faLandmark,
    faLaptop,
    faLaptopCode,
    faLocationDot,
    faLock,
    faMagnifyingGlass,
    faMobile,
    faMoneyBill,
    faMoon,
    faMosquito,
    faMotorcycle,
    faMountainSun,
    faMugHot,
    faMugSaucer,
    faMusic,
    faOm,
    faPaintRoller,
    faPaperclip,
    faPenNib,
    faPenToSquare,
    faPeopleRoof,
    faPersonBiking,
    faPersonDigging,
    faPersonHiking,
    faPersonSwimming,
    faPersonWalking,
    faPersonWalkingLuggage,
    faPhone,
    faPizzaSlice,
    faPlane,
    faRadio,
    faRoad,
    faRoute,
    faSeedling,
    faShield,
    faShip,
    faShirt,
    faShoePrints,
    faShop,
    faShower,
    faSprayCanSparkles,
    faStar,
    faStore,
    faSuitcaseRolling,
    faSun,
    faTablets,
    faTag,
    faTaxi,
    faTicket,
    faToilet,
    faTrain,
    faTrainSubway,
    faTrainTram,
    faTree,
    faTv,
    faUmbrella,
    faUser,
    faUserDoctor,
    faUserGroup,
    faUserNurse,
    faUserSecret,
    faUsers,
    faUtensils,
    faVideo,
    faWallet,
    faWheatAwn,
    faWifi,
    faWineGlass
} from '@fortawesome/free-solid-svg-icons'

const icon = [

    { icon: faBriefcase, label: "Briefcase", value: "faBriefcase" },
    { icon: faHandHoldingHeart, label: "HandHoldingHeart", value: "faHandHoldingHeart" },
    { icon: faBookOpenReader, label: "BookOpenReader", value: "faBookOpenReader" },
    { icon: faShower, label: "Shower", value: "faShower" },
    { icon: faHandPointDown, label: "HandPointDown", value: "faHandPointDown" },
    { icon: faDesktop, label: "Desktop", value: "faDesktop" },
    { icon: faBroomBall, label: "BroomBall", value: "faBroomBall" },
    { icon: faHotel, label: "Hotel", value: "faHotel" },
    { icon: faTrainSubway, label: "TrainSubway", value: "faTrainSubway" },
    { icon: faPeopleRoof, label: "PeopleRoof", value: "faPeopleRoof" },
    { icon: faShopify, label: "Shopify", value: "faShopify" },
    { icon: faItunesNote, label: "ItunesNote", value: "faItunesNote" },
    { icon: faAudible, label: "Audible", value: "faAudible" },
    { icon: faHouse, label: 'House', value: 'faHouse' },
    { icon: faUser, label: 'User', value: 'faUser' },
    { icon: faFacebook, label: 'Facebook', value: 'faFacebook' },
    { icon: faImage, label: 'Image', value: 'faImage' },
    { icon: faPhone, label: 'Phone', value: 'faPhone' },
    { icon: faInstagram, label: 'Instagram', value: 'faInstagram' },
    { icon: faEnvelope, label: 'Envelope', value: 'faEnvelope' },
    { icon: faLinkedin, label: 'Linkedin', value: 'faLinkedin' },
    { icon: faStar, label: 'Star', value: 'faStar' },
    { icon: faLocationDot, label: 'LocationDot', value: 'faLocationDot' },
    { icon: faMusic, label: 'Music', value: 'faMusic' },
    { icon: faHeart, label: 'Heart', value: 'faHeart' },
    { icon: faDiscord, label: 'Discord', value: 'faDiscord' },
    { icon: faYoutube, label: 'Youtube', value: 'faYoutube' },
    { icon: faComment, label: 'Comment', value: 'faComment' },
    { icon: faPenNib, label: 'PenNib', value: 'faPenNib' },
    { icon: faCalendarDays, label: 'CalendarDays', value: 'faCalendarDays' },
    { icon: faPaperclip, label: 'Paperclip', value: 'faPaperclip' },
    { icon: faBell, label: 'Bell', value: 'faBell' },
    { icon: faFilter, label: 'Filter', value: 'faFilter' },
    { icon: faBolt, label: 'Bolt', value: 'faBolt' },
    { icon: faCar, label: 'Car', value: 'faCar' },
    { icon: faApple, label: 'Apple', value: 'faApple' },
    { icon: faMugHot, label: 'MugHot', value: 'faMugHot' },
    { icon: faCircleUser, label: 'CircleUser', value: 'faCircleUser' },
    { icon: faGoogle, label: 'Google', value: 'faGoogle' },
    { icon: faUmbrella, label: 'Umbrella', value: 'faUmbrella' },
    { icon: faGift, label: 'Gift', value: 'faGift' },
    { icon: faLock, label: 'Lock', value: 'faLock' },
    { icon: faWindows, label: 'Windows', value: 'faWindows' },
    { icon: faHeadphones, label: 'Headphones', value: 'faHeadphones' },
    { icon: faTag, label: 'Tag', value: 'faTag' },
    { icon: faBook, label: 'Book', value: 'faBook' },
    { icon: faCamera, label: 'Camera', value: 'faCamera' },
    { icon: faVideo, label: 'Video', value: 'faVideo' },
    { icon: faDroplet, label: 'Droplet', value: 'faDroplet' },
    { icon: faPenToSquare, label: 'PenToSquare', value: 'faPenToSquare' },
    { icon: faCircleExclamation, label: 'CircleExclamation', value: 'faCircleExclamation' },
    { icon: faEye, label: 'Eye', value: 'faEye' },
    { icon: faPlane, label: 'Plane', value: 'faPlane' },
    { icon: faHand, label: 'Hand', value: 'faHand' },
    { icon: faFolder, label: 'Folder', value: 'faFolder' },
    { icon: faMoneyBill, label: 'MoneyBill', value: 'faMoneyBill' },
    { icon: faComments, label: 'Comments', value: 'faComments' },
    { icon: faKey, label: 'Key', value: 'faKey' },
    { icon: faCode, label: 'Code', value: 'faCode' },
    { icon: faCity, label: 'City', value: 'faCity' },
    { icon: faTicket, label: 'Ticket', value: 'faTicket' },
    { icon: faTree, label: 'Tree', value: 'faTree' },
    { icon: faFire, label: 'Fire', value: 'faFire' },
    { icon: faWifi, label: 'Wifi', value: 'faWifi' },
    { icon: faMagnifyingGlass, label: 'MagnifyingGlass', value: 'faMagnifyingGlass' },
    { icon: faPaintRoller, label: 'PaintRoller', value: 'faPaintRoller' },
    { icon: faBicycle, label: 'Bicycle', value: 'faBicycle' },
    { icon: faCheck, label: 'Check', value: 'faCheck' },
    { icon: faHashtag, label: 'Hashtag', value: 'faHashtag' },
    { icon: faAddressBook, label: 'AddressBook', value: 'faAddressBook' },
    { icon: faBath, label: 'Bath', value: 'faBath' },
    { icon: faUsers, label: 'Users', value: 'faUsers' },
    { icon: faGamepad, label: 'Gamepad', value: 'faGamepad' },
    { icon: faSun, label: 'Sun', value: 'faSun' },
    { icon: faFish, label: 'Fish', value: 'faFish' },
    { icon: faBug, label: 'Bug', value: 'faBug' },
    { icon: faMugSaucer, label: 'MugSaucer', value: 'faMugSaucer' },
    { icon: faShop, label: 'Shop', value: 'faShop' },
    { icon: faBuilding, label: 'Building', value: 'faBuilding' },
    { icon: faStore, label: 'Store', value: 'faStore' },
    { icon: faLandmark, label: 'Landmark', value: 'faLandmark' },
    { icon: faShirt, label: 'Shirt', value: 'faShirt' },
    { icon: faBagShopping, label: 'BagShopping', value: 'faBagShopping' },
    { icon: faUserSecret, label: 'UserSecret', value: 'faUserSecret' },
    { icon: faCarSide, label: 'CarSide', value: 'faCarSide' },
    { icon: faCableCar, label: 'CableCar', value: 'faCableCar' },
    { icon: faMountainSun, label: 'MountainSun', value: 'faMountainSun' },
    { icon: faClock, label: 'Clock', value: 'faClock' },
    { icon: faCreditCard, label: 'CreditCard', value: 'faCreditCard' },
    { icon: faMobile, label: 'Mobile', value: 'faMobile' },
    { icon: faFlag, label: 'Flag', value: 'faFlag' },
    { icon: faShield, label: 'Shield', value: 'faShield' },
    { icon: faAddressCard, label: 'AddressCard', value: 'faAddressCard' },
    { icon: faUserNurse, label: 'UserNurse', value: 'faUserNurse' },
    { icon: faLaptop, label: 'Laptop', value: 'faLaptop' },
    { icon: faMoon, label: 'Moon', value: 'faMoon' },
    { icon: faDoorOpen, label: 'DoorOpen', value: 'faDoorOpen' },
    { icon: faBrain, label: 'Brain', value: 'faBrain' },
    { icon: faWallet, label: 'Wallet', value: 'faWallet' },
    { icon: faShip, label: 'Ship', value: 'faShip' },
    { icon: faMotorcycle, label: 'Motorcycle', value: 'faMotorcycle' },
    { icon: faSeedling, label: 'Seedling', value: 'faSeedling' },
    { icon: faTrain, label: 'Train', value: 'faTrain' },
    { icon: faHospital, label: 'Hospital', value: 'faHospital' },
    { icon: faRadio, label: 'Radio', value: 'faRadio' },
    { icon: faRoute, label: 'Route', value: 'faRoute' },
    { icon: faRoad, label: 'Road', value: 'faRoad' },
    { icon: faBaby, label: 'Baby', value: 'faBaby' },
    { icon: faGopuram, label: 'Gopuram', value: 'faGopuram' },
    { icon: faIndustry, label: 'Industry', value: 'faIndustry' },
    { icon: faTablets, label: 'Tablets', value: 'faTablets' },
    { icon: faDumbbell, label: 'Dumbbell', value: 'faDumbbell' },
    { icon: faWineGlass, label: 'WineGlass', value: 'faWineGlass' },
    { icon: faWheatAwn, label: 'WheatAwn', value: 'faWheatAwn' },
    { icon: faUtensils, label: 'Utensils', value: 'faUtensils' },
    { icon: faUserGroup, label: 'UserGroup', value: 'faUserGroup' },
    { icon: faUserDoctor, label: 'UserDoctor', value: 'faUserDoctor' },
    { icon: faTv, label: 'Tv', value: 'faTv' },
    { icon: faTrainTram, label: 'TrainTram', value: 'faTrainTram' },
    { icon: faToilet, label: 'Toilet', value: 'faToilet' },
    { icon: faTaxi, label: 'Taxi', value: 'faTaxi' },
    { icon: faSuitcaseRolling, label: 'SuitcaseRolling', value: 'faSuitcaseRolling' },
    { icon: faSprayCanSparkles, label: 'SprayCanSparkles', value: 'faSprayCanSparkles' },
    { icon: faShoePrints, label: 'ShoePrints', value: 'faShoePrints' },
    { icon: faPizzaSlice, label: 'PizzaSlice', value: 'faPizzaSlice' },
    { icon: faPersonWalking, label: 'PersonWalking', value: 'faPersonWalking' },
    { icon: faPersonWalkingLuggage, label: 'PersonWalkingLuggage', value: 'faPersonWalkingLuggage' },
    { icon: faPersonSwimming, label: 'PersonSwimming', value: 'faPersonSwimming' },
    { icon: faPersonHiking, label: 'PersonHiking', value: 'faPersonHiking' },
    { icon: faPersonDigging, label: 'PersonDigging', value: 'faPersonDigging' },
    { icon: faPersonBiking, label: 'PersonBiking', value: 'faPersonBiking' },
    { icon: faOm, label: 'Om', value: 'faOm' },
    { icon: faMosquito, label: 'Mosquito', value: 'faMosquito' },
    { icon: faLaptopCode, label: 'LaptopCode', value: 'faLaptopCode' },
    { icon: faInfinity, label: 'Infinity', value: 'faInfinity' },
    { icon: faHourglassHalf, label: 'HourglassHalf', value: 'faHourglassHalf' },
    { icon: faIceCream, label: 'IceCream', value: 'faIceCream' },
    { icon: faHandPeace, label: 'HandPeace', value: 'faHandPeace' },
    { icon: faHandMiddleFinger, label: 'HandMiddleFinger', value: 'faHandMiddleFinger' },
    { icon: faGlassWater, label: 'GlassWater', value: 'faGlassWater' },
    { icon: faGasPump, label: 'GasPump', value: 'faGasPump' },
    { icon: faEarthAsia, label: 'EarthAsia', value: 'faEarthAsia' },
    { icon: faCouch, label: 'Couch', value: 'faCouch' },
    { icon: faClapperboard, label: 'Clapperboard', value: 'faClapperboard' },
    { icon: faChartGantt, label: 'ChartGantt', value: 'faChartGantt' },
    { icon: faBusSimple, label: 'BusSimple', value: 'faBusSimple' },
    { icon: faBurger, label: 'Burger', value: 'faBurger' },
    { icon: faBroom, label: 'Broom', value: 'faBroom' },
    { icon: faBellConcierge, label: 'BellConcierge', value: 'faBellConcierge' },
    { icon: faBed, label: 'Bed', value: 'faBed' },
]
export default icon 